version: 0.2

phases:
  build:
    commands:
      - aws --version
      - NEW_TAG=$(git --no-pager tag --points-at $CODEBUILD_RESOLVED_SOURCE_VERSION)
      - cd ${CODEBUILD_SRC_DIR_teDockerBuild}
      - cd codepipeline/parser-pipeline/
      - echo "Updating parser version"
      - ./set_env_parser_version.sh test-tfvars "$NEW_TAG"
      - echo "Updating lambda versions"
      - aws configure --profile non-prod set role_arn "${NON_PROD_ROLE_ARN}"
      - aws configure --profile non-prod set credential_source EcsContainer
      - ACCOUNT_ID="$(aws sts get-caller-identity --profile non-prod --query Account --output text)"
      - IMAGE_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_PARSER_IMAGE_NAME:$NEW_TAG
      - aws lambda update-function-code --function-name test-tre-run-judgment-parser --image-uri $IMAGE_URI --profile non-prod
      - echo "Running regression tests"
      - cd ../../testing/tre_module_test/
      - aws configure --profile managment set role_arn "${MANAGMENT_ROLE_ARN}"
      - aws configure --profile managment set credential_source EcsContainer
      - echo "${TEST_ENV_CONFIG}" | tee test_env_config.json
      - echo "${TEST_CONSIGNMENTS}" | tee test_consignments.json
      - python3 tre_module_test.py "${S3_TEST_DATA_BUCKET}" "test_env_config.json" "test_consignments.json" "managment" "non-prod"
