version: 0.2

#env:
#  variables:
#    key: "value"
#    key: "value"

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y curl jq sudo
      - wget https://releases.hashicorp.com/terraform/1.0.10/terraform_1.0.10_linux_amd64.zip
      - unzip terraform_1.0.10_linux_amd64.zip
      - sudo mv terraform /bin
      - rm terraform_1.0.10_linux_amd64.zip
      - echo "Prepare terraform file"
      - cd common
      - echo 'bucket          = "da-transform-terraform-state"' > backend.conf
      - echo 'key             = "environments/common/terraform.tfstate"' >> backend.conf
      - echo 'region          = "eu-west-2"' >> backend.conf
      - echo 'dynamodb_table  = "da-transform-terraform-state"' >> backend.conf
      - echo 'encrypt         = true' >> backend.conf
      - cat backend.conf
      - terraform init -backend-config=backend.conf -reconfigure
  build:
    commands:
      - echo "Terraform plan follows..."
      - terraform plan
      - echo "Terraform plan complete"
  post_build:
    commands:
      - echo "Nothing to do in the post_build for now"
