version: 0.2

phases:
  build:
    commands:
       - echo Running regression tests....
       - cd ${CODEBUILD_SRC_DIR_teDockerBuild}
       - cd testing/tre_module_test
       - ls
       - echo "${TEST_ENV_CONFIG}" | tee test_env_config.json
       - cat test_env_config.json
       - echo "${TEST_CONSIGNMENTS}" | tee test_consignments.json
       - cat test_consignments.json
       - echo "${TEST_ENV_CONFIG}"