version: 0.2

phases:
  install:
    commands:
      - set -o pipefail
      - ./install.sh
      - echo "Prepare terraform file"
      - echo ${CODEBUILD_SRC_DIR}
      - echo ${CODEBUILD_SRC_DIR_TerraformDev}
      - ls -la ${CODEBUILD_SRC_DIR}
      - ls -la ${CODEBUILD_SRC_DIR_TerraformDev}
      - cp -R ../../da-transform-terraform-modules ../da-transform-terraform-modules
      - pwd
      - cd deployments
      - echo "${TERRAFORM_BACKEND_CONF}" | tee backend.conf
      - cat backend.conf
      - echo "${TERRAFORM_VARS}" | tee terraform.tfvars.json
      - cat terraform.tfvars.json
      - terraform init -backend-config=backend.conf -upgrade -reconfigure
  build:
    commands:
      - echo "Terraform plan follows..."
      - terraform plan -var-file="terraform.tfvars.json" -out plan.out
      - ls -la
      - echo "Terraform plan complete"
  post_build:
    commands:
      - echo "Running tfsec..."
      - set -o pipefail
      - tfsec --soft-fail --no-colour --format json --tfvars-file terraform.tfvars.json | tee tfsec-out.json
      - echo "Completed tfsec"
      - echo "File listing:"
      - ls -larth
artifacts:
  files:
    - "plan.out"
    - "tfsec-out.json"
    - ".terraform/**/*"
    - ".terraform.lock.hcl"
  base-directory: "deployments"
  name: "plan_output"
