version: 0.2

phases:
  install:
    commands:
      - ls -la $CODEBUILD_SRC_DIR_source_output
      - ls -la $CODEBUILD_SRC_DIR_plan_output
      - ls -la ../../../
      - ls -la ../../s3
      - cat {$CODEBUILD_SRC_DIR}
      - ls -la ../../github.com
      - ls -la ../../github.com/nationalarchives
      - ls -la ../../github.com/nationalarchives/da-transform-terraform-modules
      - cp -vr -t deployments $CODEBUILD_SRC_DIR_plan_output/plan.out $CODEBUILD_SRC_DIR_plan_output/.terraform*
      - cp -R ../../github.com/nationalarchives/da-transform-terraform-modules ../da-transform-terraform-modules
      - pwd
      - set -o pipefail
      - ./install.sh
      - echo "Prepare terraform file"
      - cd deployments
      - ls -la
      - echo "${TERRAFORM_BACKEND_CONF}" | tee backend.conf
      - cat backend.conf
      - echo "${TERRAFORM_VARS}" | tee terraform.tfvars.json
      - cat terraform.tfvars.json
  build:
    commands:
      - echo "Terraform apply follows..."
      - terraform apply -input=false plan.out > apply.out
      - echo $?
      - cat apply.out
      - echo "Terraform apply complete"
artifacts:
  files:
    - apply.out
  name: plan-output
cache:
  paths:
    - .terraform
    - .terraform.lock.hcl
