version: 0.2

#env:
#  variables:
#    key: "value"
#    key: "value"

phases:
  install:
    commands:
      - ./install.sh
  build:
    commands:
      - echo "Start the unit tests for the terraform modules"
      - echo "Prepare terraform file"
      - cd common
      - echo "${TERRAFORM_BACKEND_CONF}" > backend.conf
      - echo "${TERRAFORM_VARS}" > terraform.tfvars
      - cat backend.conf
      - terraform init -backend-config=backend.conf -reconfigure
      - echo "Terraform plan follows..."
      - terraform plan -var-file="terraform.tfvars" -out plan.out
      - terraform apply -auto-approve
      - echo "Terraform plan complete"
  post_build:
    commands:
      - echo "Nothing to do in the post_build for now"
reports:
  terratest-reports:
    files:
      - "**/*.xml"
      - "**/*.log"
    base-directory: "../da-transform-terraform-modules/test/reports"
    discard-paths: no
artifacts:
  files:
    - plan.out
  name: plan-output
cache:
  paths:
    - .terraform
